baseURL = 'http://humzakt.github.io/'
languageCode = 'en-us'
title = 'Stuff By Humza'
 theme = "anatole"
enableEmoji = true


[params]
 title = "Stuff By Humza"
 author = "Humza Tareen"
 description = "Blogs, Tips and other stuff"
  profilePicture = "images/pic.jpg"
   mainSections = ["blog"]
