baseurl = "http://humzakt.github.io"
title = "Stuff By Humza"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true



[params]
  author = "Humza Tareen"
  info = ["CyberSecurity Enthusiast | Web & Mobile Developer"]
  description = "Humza Tareen's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/pic.jpg"
#  gravatar = "humzakhawartareen@gmail.com"

dateFormat = "January 2, 2006"
  since = 2022

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false









[params.csp]
childsrc = ["'self'"]
fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
formaction = ["'self'"]
framesrc = ["'self'"]
imgsrc = ["'self'"]
objectsrc = ["'none'"]
stylesrc = [
  "'self'",
  "'unsafe-inline'",
  "https://fonts.googleapis.com/",
  "https://cdn.jsdelivr.net/"
]
scriptsrc = [
  "'self'",
  "'unsafe-inline'",
  "https://www.google-analytics.com",
  "https://cdn.jsdelivr.net/"
]
prefetchsrc = ["'self'"]
# connect-src directive – defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
connectsrc = ["'self'", "https://www.google-analytics.com"]


[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "Humza Tareen"

[params.googleTagManager]
    id = "G-9TWYCEB2L9"

# Social links
[[params.social]]
  name = "Linkedin"
  icon = "fa fa-linkedin fa-2x"
  weight = 1
  url = "https://linkedin.com/in/humzakt/"

[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 2
  url = "https://github.com/humzakt/"

[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/humzakt/"
  [[params.social]]
  name = "Discord"
  icon = "fa fa-discord fa-2x"
  weight = 4
  url = "https://discord.com/users/humzakt"
 

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
[[menu.main]]
  name = "Resume"
  weight = 3
  url = "resume/"
  [[menu.main]]
  name = "Projects"
  weight = 3
  url = "resume/#projects"
[[menu.main]]
  name = "Contact Me"
  weight = 4
  url = "resume/#contact-details"
