baseurl = "http://humzakt.github.io"
title = "Stuff By Humza"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = ""

[params]
  author = "Humza Tareen"
  info = "CyberSecurity Enthusiast | Web & Mobile Dev"
  description = "Humza Tareen's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/pic.jpg"
#  gravatar = "humzakhawartareen@gmail.com"

  favicon_32 = "fa fa-twitter fa-2x"
  favicon_16 = "fa fa-twitter fa-2x"

  since = 2022

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "Humza Tareen"

[params.googleTagManager]
    id = "G-9TWYCEB2L9"

# Social links
[[params.social]]
  name = "Linkedin"
  icon = "fa fa-linkedin fa-2x"
  weight = 1
  url = "https://linkedin.com/in/humzakt/"

[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 2
  url = "https://github.com/humzakt/"

[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/humzakt/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
[[menu.main]]
  name = "Projects"
  weight = 3
  url = "projects/"
[[menu.main]]
  name = "Contact"
  weight = 4
  url = "contact/"